### ISSUE TITLE
电影数据加载不出来

### ISSUE THREAD

**Issue by yang302** [yllg/WXxcx#1]
请问下，电影数据加载不出了？

**Comment by LimWestIce** [comment]
api.douban.com 改成 douban.uieee.com

**Comment by lataaaa** [comment]
请问下在定位城市的时候，这个代码res.data.result.ad_info.city  报
Cannot read property 'ad_info' of undefined;at pages/switchcity/switchcity onReady function;at api request success callback function
TypeError: Cannot read property 'ad_info' of undefined  ，刚刚接触小程序，这个回调函数类型错误能告诉我怎么解决吗，拜托了

**Comment by geLouTingFengSheng** [comment]
这是说'ad_info'未定义,你可以先把 res.data.result 打印出来看看里面有哪些属性可用, 从而进行分析如何取数
